import React, { useState, useEffect, useRef } from "react";
import {
  View,
  Text,
  Pressable,
  StyleSheet,
  Animated,
  Modal,
  ScrollView
} from "react-native";
import { useNavigation } from "@react-navigation/native";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";
import Ionicons from "react-native-vector-icons/Ionicons";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { TouchableWithoutFeedback } from "react-native";

const GLASS_BG = "rgba(255,255,255,0.08)";
const GLASS_BORDER = "rgba(255,255,255,0.15)";
const GLASS_TEXT = "#E5E5EA";
const GLASS_SUBTEXT = "#A1A1A6";
const ACCENT = "#F5C77A";

const SubscriptionScreen = ({ autoOpen = true, onClose }) => {
  const navigation = useNavigation();
  const insets = useSafeAreaInsets();

  const [selectedPlan, setSelectedPlan] = useState("1");
  const [loginPopup, setLoginPopup] = useState(false);
  const [trialEnabled, setTrialEnabled] = useState(false);
  const [successPopup, setSuccessPopup] = useState(false);
  const [policyVisible, setPolicyVisible] = useState(false);
  const [policyType, setPolicyType] = useState(null);
  const openPolicy = (type) => {
    setPolicyType(type);
    setPolicyVisible(true);
  };
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const TERMS_TEXT = `
  Last updated: ${today}

Welcome to Captions, operated by Phonato Studios.

By accessing or using the Captions mobile application, you agree to be bound by these Terms of Use. If you do not agree, please do not use the app.

1. Subscriptions & Payments
Captions offers subscription-based features billed on a monthly or yearly basis. Payment will be charged to your account at confirmation of purchase.

Subscriptions automatically renew unless auto-renew is turned off at least 24 hours before the end of the current period. You can manage or cancel subscriptions through your account settings.

Any unused portion of a free trial will be forfeited upon purchasing a subscription.

2. Acceptable Use
You agree not to misuse the app, attempt to reverse engineer it, or use it for unlawful purposes.

3. Intellectual Property
All content, features, and technology within Captions are owned by Phonato Studios and protected by applicable laws.

4. AI Content Disclaimer
Content generated by Captions is for informational and creative purposes only. Phonato Studios makes no guarantees regarding accuracy or suitability.

5. Limitation of Liability
To the maximum extent permitted by law, Phonato Studios shall not be liable for any damages arising from your use of the app.

6. Termination
We reserve the right to suspend or terminate access if these Terms are violated.

7. Changes
These Terms may be updated at any time. Continued use of the app constitutes acceptance of the updated Terms.

8. Contact
For questions, contact Phonato Studios at support@phonatostudios.com.
`;

  const PRIVACY_TEXT = `
Last updated: ${today}

Captions is operated by Phonato Studios. Your privacy is important to us.

1. Information We Collect
We may collect account information, usage data, and device information to operate and improve the app.

2. Use of Information
Your information is used to provide services, process subscriptions, improve features, and offer support.

3. Data Sharing
We do not sell personal data. Information may be shared only with trusted service providers when necessary.

4. Security
We take reasonable measures to protect your data, but no system is completely secure.

5. User Rights
You may request access, correction, or deletion of your personal data by contacting us.

6. Changes
This Privacy Policy may be updated periodically. Continued use of the app indicates acceptance.

7. Contact
If you have questions, contact Phonato Studios at support@phonatostudios.com.
`;


  const glowAnimation = useRef(new Animated.Value(0.95)).current;
  const successAnim = useRef(new Animated.Value(0)).current;

  const plans = [
    { id: "1", title: "Monthly", price: "$9.99", period: "/month", tag: "POPULAR" },
    { id: "2", title: "Yearly", price: "$59.99", period: "/year", tag: "SAVE 50%" },
  ];

  useEffect(() => {
    Animated.loop(
      Animated.sequence([
        Animated.timing(glowAnimation, { toValue: 1, duration: 1000, useNativeDriver: true }),
        Animated.timing(glowAnimation, { toValue: 0.95, duration: 1000, useNativeDriver: true }),
      ])
    ).start();
  }, []);

  const handleToggleFreeTrial = () => setTrialEnabled(!trialEnabled);

  const handleSubscribe = async () => {
    const token = await AsyncStorage.getItem("token");

    if (!token) {
      setLoginPopup(true);
      return;
    }

    const sku = selectedPlan === "1" ? "monthly_plan" : "yearly_plan";

    try {
      const now = Date.now();
      let trialEndDate = null;

      if (trialEnabled) {
        trialEndDate = now + 7 * 24 * 60 * 60 * 1000;

        await fetch("https://my-ai-captions.onrender.com/api/subscription/start-trial", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ productId: sku }),
        });
      }

      let premiumStartDate = trialEnabled ? trialEndDate : now;

      let expiryDate =
        selectedPlan === "1"
          ? premiumStartDate + 30 * 24 * 60 * 60 * 1000
          : premiumStartDate + 365 * 24 * 60 * 60 * 1000;

      await fetch("https://my-ai-captions.onrender.com/api/subscription/verify", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          productId: sku,
          purchaseToken: "TEST",
          transactionId: "TEST",
          expiryDate,
          platform: "test_mode",
        }),
      });

      setSuccessPopup(true);
      successAnim.setValue(0);

      Animated.spring(successAnim, {
        toValue: 1,
        useNativeDriver: true,
        friction: 6,
      }).start();

      setTimeout(() => {
        setSuccessPopup(false);
        navigation.reset({
          index: 0,
          routes: [{ name: "Home" }],
        });
      }, 1500);
    } catch (error) {
      console.log("Subscription Error:", error);
    }
  };

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: "#141414ff" }}>

      {/* SAFE CLOSE BUTTON */}
      <View
        style={{
          position: "absolute",
          top: insets.top,
          right: 0,
          zIndex: 10,
        }}
      >
        <Pressable style={styles.closeBtn} onPress={onClose || (() => navigation.goBack())}>
          <Ionicons name="close" size={28} color="#b5b5b5" />
        </Pressable>
      </View>

      <ScrollView
        contentContainerStyle={[
          styles.container,
          {
            paddingTop: styles.container.paddingTop + insets.top,
            paddingBottom: insets.bottom,
          },
        ]}
        showsVerticalScrollIndicator={false}
      >

        <View style={styles.headerBox}>
          <Text style={styles.title}>Go Premium ✨</Text>
          <Text style={styles.subtitle}>Unlock unlimited captions & AI features</Text>
        </View>

        <View style={styles.featureBox}>
          {[
            "Unlimited caption generation",
            "No daily limits",
            "All moods & languages",
            "Priority response speed",
          ].map((item, index) => (
            <View key={index} style={styles.featureRow}>
              <Ionicons name="checkmark-circle" size={20} color="#F5C77A" style={{ marginRight: 8 }} />
              <Text style={styles.featureText}>{item}</Text>
            </View>
          ))}
        </View>

        <View style={styles.freeTrial}>
          <Text style={styles.freeTrialText}>✨ 7 Days Free Trial Available ✨</Text>
        </View>

        <View style={[styles.trialRow, trialEnabled && {
          backgroundColor: "rgba(245,199,122,0.22)",
          borderColor: ACCENT,
        }]}>
          <Text style={styles.trialTextLeft}>Enable Free Trial</Text>

          <Pressable onPress={handleToggleFreeTrial}>
            <View style={[styles.switchTrack, trialEnabled ? styles.switchTrackOn : styles.switchTrackOff]}>
              <Animated.View
                style={[
                  styles.switchThumb,
                  { transform: [{ translateX: trialEnabled ? 22 : 2 }] }
                ]}
              />
            </View>
          </Pressable>
        </View>

        <View style={{ width: "100%", marginTop: 20 }}>
          {plans.map((plan) => (
            <Pressable
              key={plan.id}
              style={[
                styles.planCard,
                selectedPlan === plan.id && selectedPlan === plan.id && {
                  backgroundColor: "rgba(245,199,122,0.22)",
                  borderColor: ACCENT,
                }
              ]}
              onPress={() => setSelectedPlan(plan.id)}
            >
              <View>
                <Text style={styles.planTitle}>{plan.title}</Text>
                <Text style={styles.planPrice}>
                  {plan.price}<Text style={styles.planPeriod}>{plan.period}</Text>
                </Text>
              </View>

              <View style={styles.tagBox}>
                <Text style={styles.tagText}>{plan.tag}</Text>
              </View>
            </Pressable>
          ))}
        </View>

        <Animated.View style={{ transform: [{ scale: glowAnimation }] }}>
          <Pressable style={styles.subscribeBtn} onPress={handleSubscribe}>
            <Text style={styles.subscribeText}>Upgrade Now</Text>
          </Pressable>
        </Animated.View>

      </ScrollView>

      <View
        style={[
          styles.bottomPolicyContainer,
          { paddingBottom: insets.bottom + 12 },
        ]}
      >
        <View style={styles.bottomPolicyRow}>
          <Pressable onPress={() => openPolicy("terms")}>
            <Text style={styles.bottomPolicyText}>Terms of Use</Text>
          </Pressable>

          <Text style={styles.bottomPolicyBullet}>•</Text>

          <Pressable onPress={() => console.log("Restore pressed")}>
            <Text style={styles.bottomPolicyText}>Restore Purchases</Text>
          </Pressable>

          <Text style={styles.bottomPolicyBullet}>•</Text>

          <Pressable onPress={() => openPolicy("privacy")}>
            <Text style={styles.bottomPolicyText}>Privacy Policy</Text>
          </Pressable>
        </View>
      </View>

      <Modal
        visible={policyVisible}
        transparent
        animationType="slide"
        onRequestClose={() => setPolicyVisible(false)}
      >
        <View style={styles.policyOverlay}>

          {/* OUTSIDE TAP AREA */}
          <Pressable
            style={styles.policyBackdrop}
            onPress={() => setPolicyVisible(false)}
          />

          {/* BOTTOM SHEET */}
          <View
            style={[
              styles.policySheet,
              { paddingBottom: insets.bottom + 16 },
            ]}
          >
            <Text style={styles.policyTitle}>
              {policyType === "terms" ? "Terms of Use" : "Privacy Policy"}
            </Text>

            <ScrollView
              showsVerticalScrollIndicator={false}
              contentContainerStyle={{ paddingBottom: 32 }}
            >
              <Text style={styles.policyContent}>
                {policyType === "terms" ? TERMS_TEXT : PRIVACY_TEXT}
              </Text>
            </ScrollView>
          </View>

        </View>
      </Modal>


      {/* POPUPS */}
      <Modal visible={loginPopup} transparent animationType="fade">
        <Pressable
          style={styles.popupOverlay}
          onPress={() => setLoginPopup(false)}
        >
          <Pressable
            style={styles.popupBox}
            onPress={(e) => e.stopPropagation()}
          >
            <Text style={styles.popupTitle}>Login Required</Text>
            <Text style={styles.popupDesc}>Please login to continue.</Text>

            <Pressable
              style={styles.loginBtn}
              onPress={() => {
                setLoginPopup(false);
                navigation.navigate("Login");
              }}
            >
              <Text style={styles.loginBtnText}>Login</Text>
            </Pressable>

            <Pressable onPress={() => setLoginPopup(false)} style={{ marginTop: 10 }}>
              <Text style={{ color: "#bbb" }}>Cancel</Text>
            </Pressable>
          </Pressable>
        </Pressable>
      </Modal>


      <Modal visible={successPopup} transparent>
        <View style={styles.popupOverlay}>
          <Animated.View
            style={[
              styles.successBox,
              {
                transform: [
                  {
                    scale: successAnim.interpolate({
                      inputRange: [0, 1],
                      outputRange: [0.5, 1],
                    }),
                  },
                ],
                opacity: successAnim,
              },
            ]}
          >
            <Ionicons name="checkmark-circle" size={60} color="#F5C77A" />
            <Text style={styles.successText}>Subscription Activated!</Text>
          </Animated.View>
        </View>
      </Modal>

    </SafeAreaView>
  );
};

export default SubscriptionScreen;


const styles = StyleSheet.create({
  container: {
    backgroundColor: "#141414ff",
    paddingHorizontal: 20,
    justifyContent: "flex-start",
    paddingTop: 50,
  },
  closeBtn: {
    padding: 10,
    marginTop: 10,
    marginRight: 10
  },
  freeTrial: {
    alignSelf: "center",
    backgroundColor: GLASS_BG,
    borderColor: ACCENT,
    borderWidth: 1,
    paddingHorizontal: 20,
    paddingVertical: 6,
    borderRadius: 15,
    marginBottom: 10,
  },

  freeTrialText: { color: "#F5C77A", fontSize: 13, fontWeight: "700" },
  headerBox: { alignItems: "center", marginVertical: 20 },
  title: { color: "white", fontSize: 32, fontWeight: "700", marginBottom: 4 },
  subtitle: { color: "#b5b5b5", fontSize: 15 },
  featureBox: { marginBottom: 20, marginTop: 0, color: GLASS_TEXT, },
  featureRow: { flexDirection: "row", alignItems: "center", marginVertical: 6 },
  featureText: { color: "white", fontSize: 14 },

  trialRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 10,
    width: "100%",
    backgroundColor: GLASS_BG,
    paddingVertical: 13,
    borderRadius: 14,
    borderWidth: 1.2,
    borderColor: GLASS_BORDER,
    paddingHorizontal: 15,
  },
  trialTextLeft: { color: "#fff", fontSize: 16, fontWeight: "700" },

  switchTrack: {
    width: 50,
    height: 28,
    borderRadius: 20,
    justifyContent: "center",
    padding: 0,
  },
  switchTrackOn: { backgroundColor: "#F5C77A" },
  switchTrackOff: { backgroundColor: "#555" },
  switchThumb: {
    width: 24,
    height: 24,
    backgroundColor: "#fff",
    borderRadius: 12,
    position: "absolute",
  },

  planCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 18,
    borderRadius: 16,
    marginBottom: 12,
    backgroundColor: GLASS_BG,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
  },

  planTitle: {
    color: GLASS_TEXT,
    fontSize: 17,
    fontWeight: "600",
  },

  planPrice: {
    color: ACCENT,
    fontSize: 22,
    fontWeight: "700",
    marginTop: 3,
  },

  planPeriod: {
    color: GLASS_SUBTEXT,
    fontSize: 14,
  },

  tagBox: {
    backgroundColor: "white",
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
    alignSelf: "center",
  },
  tagText: { color: "black", fontSize: 12, fontWeight: "700" },

 subscribeBtn: {
  backgroundColor: GLASS_BG,
  borderColor: GLASS_BORDER,
  borderWidth: 1,
  paddingVertical: 14,
  borderRadius: 14,
  alignItems: "center",
  marginTop: 20
},

  subscribeText: { color: "#F5C77A", fontSize: 17, fontWeight: "700" },
  restoreText: { color: "#ffffffd2", textAlign: "center", marginTop: 12, },

  popupOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  popupBox: {
    width: 280,
    padding: 20,
    borderRadius: 12,
    backgroundColor: "rgba(30,30,30,0.92)",
    alignItems: "center",
    borderWidth: 1,
    borderColor: GLASS_BORDER,
  },
  popupTitle: { color: "#fff", fontSize: 20, fontWeight: "700", marginBottom: 8 },
  popupDesc: { color: "#bbb", fontSize: 14, textAlign: "center", marginBottom: 15 },
  loginBtn: {
    backgroundColor: "rgba(245,199,122,0.12)",
    borderWidth: 1,
    borderColor: "rgba(245,199,122,0.35)",
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 10,
  },
  loginBtnText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  successOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 999,
  },
  successBox: {
    backgroundColor: "rgba(30,30,30,0.92)",
    padding: 30,
    borderRadius: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: GLASS_BORDER,
  },
  successText: {
    color: "white",
    fontSize: 20,
    fontWeight: "700",
    marginTop: 10,
  },
  bottomPolicyContainer: {
    backgroundColor: "#141414ff",
    paddingTop: 8,
  },

  bottomPolicyRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20
  },

  bottomPolicyText: {
    color: GLASS_SUBTEXT,
    fontSize: 12,
    fontWeight: "600",
  },

  bottomPolicyBullet: {
    color: "#9b9b9b",
    marginHorizontal: 10,
    fontSize: 14,
  },
  policyOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  policyBackdrop: {
    flex: 1,
  },
policySheet: {
  height: "80%",
  backgroundColor: "#141414ff",
  borderTopLeftRadius: 20,
  borderTopRightRadius: 20,
  padding: 20,
  borderTopWidth: 1,
  borderLeftWidth: 1,
  borderRightWidth: 1,
  borderBottomWidth: 0,
  borderColor: "#F5C77A",
},



  policyTitle: {
    color: GLASS_TEXT,
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 10,
    textAlign: "center",
  },

  policyContent: {
    color: GLASS_SUBTEXT,
    fontSize: 14,
    lineHeight: 20,
  },

  policyCloseBtn: {
    marginTop: 15,
    alignItems: "center",
    paddingVertical: 12,
  },

  policyCloseText: {
    color: "#7d5df8",
    fontSize: 16,
    fontWeight: "700",
  },

});
